name: Scheduled Workflow

on:
  schedule:
    - cron: '0 22 * * *'  # Runs every day at 10:00 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script or action
        run: echo "This action Runs every day at 10:00 PM UTC!"
